### ISSUE TITLE
Does this tool match ACES 1.3 gamut compression?

### ISSUE THREAD

**Issue by RebelPhoton** [jedypod/gamut-compress#6]
Hello, I read the readme but I have a question... does this blinkscript or nuke gizmo match the same math as the official ACES 1.3 gamut compression?

In other words, I can use it in nuke to match my vfx pulls against some dailies that were generated by resolve 17 with ACES 1.3 gamut compression enabled?

**Comment by jedypod** [comment]
Hello!
> same math as the official ACES 1.3 gamut compression?

No not exactly the same math. As mentioned briefly in the readme at the end, and the [release notes for v0.7](https://github.com/jedypod/gamut-compress/releases/tag/v0.7), this version uses an improved compression function.

If you need to match "official" aces gamut compression, you should use those tools instead.

If you have additional questions don't hesitate!

**Comment by RebelPhoton** [comment]
Thanks for the quickest answer ever!

My problem is that I can't find a way to install an ACES 1.3 ocio config in nuke. The ones i've found are only compatible with OCIO 2.1 and nuke 13.1 refuses them. I've even run the ocio generator myself, but no difference. So I was looking for ways to emulate the same math without having to wait for a nuke update. Are you aware of any?

**Comment by jedypod** [comment]
I'm not really sure because I have not been closely following the ACES "Reference Gamut Compression" recommended best practices.

For more information you could try reading through the [usage guide](https://docs.acescentral.com/guides/rgc-user/). In that page it looks like it [links to](https://github.com/ampas/aces-dev/blob/master/transforms/ctl/lmt/LMT.Academy.GamutCompress.ctl) the CTL file, so maybe you could compile `ctlrender` and use that to process your images instead of Nuke?

There's also the aces-dev gamut compress repo which has a version of [the nuke node](https://github.com/ampas/aces-vwg-gamut-mapping-2020/blob/master/model/GamutCompress.nk), but I'm not sure if those parameters match the official release.

Post back if you figure it out, maybe others will have the same confusion.

**Comment by RebelPhoton** [comment]
> There's also the aces-dev gamut compress repo which has a version of [the nuke node](https://github.com/ampas/aces-vwg-gamut-mapping-2020/blob/master/model/GamutCompress.nk), but I'm not sure if those parameters match the official release.

Well, not that one, but right next to it, in a parallel folder, there was [this](https://github.com/ampas/aces-vwg-gamut-mapping-2020/tree/master/reference), labelled as the reference model and published expressly to solve my problem. Thank you so muth.

**Comment by jedypod** [comment]
Yep no worries, good luck! :slightly_smiling_face:
